/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSellInRouteImport } from './routes/_authenticated/sell-in'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedNotasFiscaisRouteImport } from './routes/_authenticated/notas-fiscais'
import { Route as AuthenticatedImportarRouteImport } from './routes/_authenticated/importar'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPorClientesIndexRouteImport } from './routes/_authenticated/por-clientes.index'
import { Route as AuthenticatedPorClientesGeralRouteImport } from './routes/_authenticated/por-clientes.geral'
import { Route as AuthenticatedPorClientesClienteIdRouteImport } from './routes/_authenticated/por-clientes.$clienteId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSellInRoute = AuthenticatedSellInRouteImport.update({
  id: '/sell-in',
  path: '/sell-in',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotasFiscaisRoute =
  AuthenticatedNotasFiscaisRouteImport.update({
    id: '/notas-fiscais',
    path: '/notas-fiscais',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportarRoute = AuthenticatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPorClientesIndexRoute =
  AuthenticatedPorClientesIndexRouteImport.update({
    id: '/por-clientes/',
    path: '/por-clientes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPorClientesGeralRoute =
  AuthenticatedPorClientesGeralRouteImport.update({
    id: '/por-clientes/geral',
    path: '/por-clientes/geral',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPorClientesClienteIdRoute =
  AuthenticatedPorClientesClienteIdRouteImport.update({
    id: '/por-clientes/$clienteId',
    path: '/por-clientes/$clienteId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/notas-fiscais': typeof AuthenticatedNotasFiscaisRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/sell-in': typeof AuthenticatedSellInRoute
  '/por-clientes/$clienteId': typeof AuthenticatedPorClientesClienteIdRoute
  '/por-clientes/geral': typeof AuthenticatedPorClientesGeralRoute
  '/por-clientes/': typeof AuthenticatedPorClientesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/notas-fiscais': typeof AuthenticatedNotasFiscaisRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/sell-in': typeof AuthenticatedSellInRoute
  '/': typeof AuthenticatedIndexRoute
  '/por-clientes/$clienteId': typeof AuthenticatedPorClientesClienteIdRoute
  '/por-clientes/geral': typeof AuthenticatedPorClientesGeralRoute
  '/por-clientes': typeof AuthenticatedPorClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/importar': typeof AuthenticatedImportarRoute
  '/_authenticated/notas-fiscais': typeof AuthenticatedNotasFiscaisRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRoute
  '/_authenticated/sell-in': typeof AuthenticatedSellInRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/por-clientes/$clienteId': typeof AuthenticatedPorClientesClienteIdRoute
  '/_authenticated/por-clientes/geral': typeof AuthenticatedPorClientesGeralRoute
  '/_authenticated/por-clientes/': typeof AuthenticatedPorClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/importar'
    | '/notas-fiscais'
    | '/pedidos'
    | '/sell-in'
    | '/por-clientes/$clienteId'
    | '/por-clientes/geral'
    | '/por-clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/dashboard'
    | '/importar'
    | '/notas-fiscais'
    | '/pedidos'
    | '/sell-in'
    | '/'
    | '/por-clientes/$clienteId'
    | '/por-clientes/geral'
    | '/por-clientes'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/importar'
    | '/_authenticated/notas-fiscais'
    | '/_authenticated/pedidos'
    | '/_authenticated/sell-in'
    | '/_authenticated/'
    | '/_authenticated/por-clientes/$clienteId'
    | '/_authenticated/por-clientes/geral'
    | '/_authenticated/por-clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sell-in': {
      id: '/_authenticated/sell-in'
      path: '/sell-in'
      fullPath: '/sell-in'
      preLoaderRoute: typeof AuthenticatedSellInRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notas-fiscais': {
      id: '/_authenticated/notas-fiscais'
      path: '/notas-fiscais'
      fullPath: '/notas-fiscais'
      preLoaderRoute: typeof AuthenticatedNotasFiscaisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/importar': {
      id: '/_authenticated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AuthenticatedImportarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/por-clientes/': {
      id: '/_authenticated/por-clientes/'
      path: '/por-clientes'
      fullPath: '/por-clientes/'
      preLoaderRoute: typeof AuthenticatedPorClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/por-clientes/geral': {
      id: '/_authenticated/por-clientes/geral'
      path: '/por-clientes/geral'
      fullPath: '/por-clientes/geral'
      preLoaderRoute: typeof AuthenticatedPorClientesGeralRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/por-clientes/$clienteId': {
      id: '/_authenticated/por-clientes/$clienteId'
      path: '/por-clientes/$clienteId'
      fullPath: '/por-clientes/$clienteId'
      preLoaderRoute: typeof AuthenticatedPorClientesClienteIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImportarRoute: typeof AuthenticatedImportarRoute
  AuthenticatedNotasFiscaisRoute: typeof AuthenticatedNotasFiscaisRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRoute
  AuthenticatedSellInRoute: typeof AuthenticatedSellInRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPorClientesClienteIdRoute: typeof AuthenticatedPorClientesClienteIdRoute
  AuthenticatedPorClientesGeralRoute: typeof AuthenticatedPorClientesGeralRoute
  AuthenticatedPorClientesIndexRoute: typeof AuthenticatedPorClientesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImportarRoute: AuthenticatedImportarRoute,
  AuthenticatedNotasFiscaisRoute: AuthenticatedNotasFiscaisRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRoute,
  AuthenticatedSellInRoute: AuthenticatedSellInRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPorClientesClienteIdRoute:
    AuthenticatedPorClientesClienteIdRoute,
  AuthenticatedPorClientesGeralRoute: AuthenticatedPorClientesGeralRoute,
  AuthenticatedPorClientesIndexRoute: AuthenticatedPorClientesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
